[build]
  publish = "/"  # Root directory where your HTML files are located
  functions = "netlify/functions"  # Directory where your serverless functions are located
  command = ""  # Skip npm build step

